services:
  app:
    image: node:lts-alpine
    user: 1000:1000
    working_dir: /app
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run test:e2e
    environment:
      DB_NAME: vibbra_test
      ACCESS_TOKEN_SECRET: abc123

  pg:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vibbra_test
    ports:
      - 5432:5432
